// Flow Compiler Types
// Compiler transforms flowchart topology + DDT into flat list of Tasks with conditions

import type { Task } from '../../types/taskTypes';
import type { Node, Edge } from 'reactflow';
import type { FlowNode, EdgeData } from '../Flowchart/types/flowTypes';
import type { AssembledTaskTree } from '../TaskTreeBuilder/DDTAssembler/currentDDT.types';

/**
 * Task State: Execution state of a task
 */
export type TaskState = 'UnExecuted' | 'Executed' | 'WaitingUserInput';

/**
 * Retrieval State: State of data retrieval in DDT
 */
export type RetrievalState = 'empty' | 'asrNoMatch' | 'asrNoInput' | 'saturated' | 'confirmed';

/**
 * Condition: Defines when a task can be executed
 */
export type Condition =
  | { type: 'Always' } // Always executable (entry node first row)
  | { type: 'TaskState'; taskId: string; state: TaskState } // Task state check
  | { type: 'RetrievalState'; state: RetrievalState } // DDT retrieval state
  | { type: 'StepActivated'; stepId: string } // Step is active
  | { type: 'EdgeCondition'; edgeId: string; condition: any } // Edge condition from flowchart
  | { type: 'And'; conditions: Condition[] } // All conditions must be true
  | { type: 'Or'; conditions: Condition[] } // At least one condition must be true
  | { type: 'Not'; condition: Condition }; // Negation (used for Else edges)

/**
 * CompiledTask: Task with condition and state for execution
 */
export interface CompiledTask {
  id: string; // Task.id (GUID) - same as row.id for flowchart tasks
  action: string; // ✅ DEPRECATED: Use templateId instead. Kept for backward compatibility.
  templateId?: string; // Task.templateId (e.g., 'SayMessage', 'DataRequest') - preferred field
  value: Record<string, any>; // Task.value
  condition: Condition | null; // Execution condition
  state: TaskState; // Current execution state
  source: {
    type: 'flowchart' | 'ddt-step' | 'ddt-recovery-action';
    nodeId?: string; // Flowchart node ID (if from flowchart)
    rowId?: string; // Flowchart row ID (if from flowchart)
    stepType?: string; // DDT step type (if from DDT)
    recoveryId?: string; // DDT recovery ID (if from recovery)
    actionId?: string; // DDT action ID (if from recovery)
    parentRowAction?: string; // Action type of parent row (DataRequest, ClassifyProblem, etc.)
  };
}

/**
 * TaskGroup: represents a node with all its tasks (rows)
 */
export interface TaskGroup {
  nodeId: string;
  execCondition?: Condition | null;
  tasks: CompiledTask[];
  executed?: boolean;
}

/**
 * Error severity levels for compilation errors
 *
 * Operational severities: 'error' | 'warning'
 * - 'error': Blocks orchestrator execution, shown with red border
 * - 'warning': Does not block execution, shown with orange border
 *
 * Future severity: 'hint'
 * - 'hint': Defined but not used yet. Reserved for future design suggestions,
 *   optimizations, and best practices from advanced flow analysis layer.
 */
export type ErrorSeverity = 'error' | 'warning' | 'hint';

/**
 * Fix target: defines where to navigate when user clicks "Fix" button
 * Generated by backend compiler - frontend must not calculate fixTarget
 */
export type FixTarget =
  | { type: 'task'; taskId: string }
  | { type: 'taskRow'; taskId: string; rowId: string }
  | { type: 'taskStep'; taskId: string; stepKey: string }
  | { type: 'taskEscalation'; taskId: string; stepKey: string; escalationIndex?: number }
  | { type: 'node'; nodeId: string }
  | { type: 'edge'; edgeId: string }
  | { type: 'condition'; conditionId: string };

/**
 * Compilation error with task/node/row context
 * Every error must have a taskId for traceability
 */
export interface CompilationError {
  taskId: string;
  nodeId?: string;
  rowId?: string;
  edgeId?: string;
  message: string;
  severity: ErrorSeverity;
  /** Stable code from compiler (e.g. MissingOrInvalidTask, AmbiguousLink, TaskCompilationFailed). */
  category?: string;
  /** Populated client-side when missing (see enrichCompilationError). */
  fixTarget: FixTarget;
  /** Row display label from backend when row-scoped. */
  rowLabel?: string;
  rowTaskRef?: string;
  resolvedTaskId?: string;
  missingTaskRef?: boolean;
  invalidType?: number;
  conditionId?: string;
  detailCode?: string;
  /** For support / detail panel — not shown as primary user copy. */
  technicalDetail?: string;
  /** AmbiguousLink: sameLabel | sameCondition | overlappingConditions | missingConditionInMultiExit */
  reason?: string;
  conflictsWith?: string[];
  entryNodeIds?: string[];
  siblingEdgeIds?: string[];
  /** Utterance step key (e.g. noMatch) when category is step/escalation scoped. */
  stepKey?: string;
  /** Zero-based escalation index within the step (EmptyEscalation). */
  escalationIndex?: number;
}

/**
 * Compilation Result: Output of compiler
 */
export interface CompilationResult {
  tasks: CompiledTask[];
  entryTaskId: string | null; // First task to execute (for frontend compatibility)
  taskMap: Map<string, CompiledTask>; // Fast lookup by task ID
  translations?: Record<string, string>; // Translation table: { translationKey: translatedText } - for runtime lookup
  // VB.NET backend fields
  taskGroups?: TaskGroup[]; // TaskGroups (one per node) - from VB.NET compiler
  entryTaskGroupId?: string | null; // First TaskGroup to execute - from VB.NET compiler
  // ✅ Error handling
  errors?: CompilationError[]; // List of compilation errors
  hasErrors?: boolean; // True if has Error (blocks orchestrator)
}

/**
 * Execution State: Runtime state for engine
 */
export interface ExecutionState {
  executedTaskIds: Set<string>;
  variableStore: Record<string, any>;
  retrievalState: RetrievalState;
  currentNodeId: string | null;
  currentRowIndex: number;
}

/**
 * DDT Expansion: Temporary nodes/edges created from DDT
 */
export interface DDTExpansion {
  parentNodeId: string; // Flowchart node that triggered DDT expansion
  stepNodes: Map<string, string>; // stepType → nodeId
  recoveryNodes: Map<string, string>; // recoveryId → nodeId
  actionTasks: Map<string, string>; // actionId → taskId
}

